name: Pipeline CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurando Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalando dependências
        run: npm install

      - name: Test
        run: npm test
